### ISSUE TITLE
Speed from ADS-B Ex is IAS not GS

### ISSUE THREAD

**Issue by MatisseBE** [Sequal32/vrclivetraffic#11]
Hi,

I noticed speeds were off by a lot. I did some digging and came to the conclution that we might have been getting IAS from ADS-B exchange instead of ground speed. Here are some examples: 

![image](https://user-images.githubusercontent.com/51272243/120072572-cbb10180-c094-11eb-80c0-abc63c3d93ad.png)
![image](https://user-images.githubusercontent.com/51272243/120072579-ceabf200-c094-11eb-877d-b09209d4db55.png)
(I noticed the pictures are blurry on Github, I advise you try this out yourself, the match one on one for me)

I'd like to add, for some aircraft this number jumps from IAS to GS all the time, for others it does not. Here's a video of that behaviour, pay attention to TRA5628. He is in the left center of the screen, his callsign is in green. The speed is encricled in yellow at the bottom left of the tag. 260 is IAS, 420 is GS.

https://www.youtube.com/watch?v=hpo2S1ialhY

**Comment by Sequal32** [comment]
Thanks! Fixed in 1.4.3!
