### ISSUE TITLE
Aircraft without three letter callsign not shown

### ISSUE THREAD

**Issue by MatisseBE** [Sequal32/vrclivetraffic#12]
Hi,

I've noticed aircraft without the "typical three letter and some numbers callsigns" don't show up. Aircraft with callsigns such as "PHBBJ", "PHPKF", "S5CNN",... are not displayed.

Here's a picture clearly showing showing that behaviour. It's shows a radar picture with all the aircraft being pulled from the application (white and green aircraft) and the FlightRadar24 website. (Both above FL180 only.) Some aircraft seen on FR24 are not visible on the radar picture.

https://prnt.sc/13l6egv
![image](https://user-images.githubusercontent.com/51272243/120100792-fc4f7480-c142-11eb-8965-02f5ac40655c.png)

I am aware flightplans are not pulled from Flightaware for callsigns like these, however I assume this should not affect whether these flights are shown or not. I have Flightaware disabled and use a range >100.

CLOSED: Problem with my Euroscope Plugin. It has a VFR filter. Why do these callsigns automatically file VFR? Sincere apologies!

**Comment by SergeiULLI** [comment]
Привет , можно объяснить с чем связано  не точные местоположения   самолётов от FR 24  и наложенной картой  ?

**Comment by SergeiULLI** [comment]
Hi, can you explain what is not the exact location of the planes from FR 24 and the superimposed map?

**Comment by MatisseBE** [comment]
It was never about exact location, but about missing aircraft. I closed this thread as I found the issue, which I also described in the first post.
