### ISSUE TITLE
VSTARS/VERAM

### ISSUE THREAD

**Issue by InfiniteFlite** [Sequal32/vrclivetraffic#2]
Can you connect this to VSTARS or VERAM? I have been looking all over for the serverlist for VSTARS/VERAM but I can't find it. Is there a way to connect this or modify the program to work with stars/eram?

**Comment by Sequal32** [comment]
Unfortunately VSTARS/VERAM utilizes a client authentication with VATSIM servers to ensure it doesn't connect to a non VATSIM server. Without modification, it's not currently possible.

**Comment by rkantos** [comment]
How about Euroscope? Cannot currently connect with or without Vatsim mode. Server seems to acknowledge both, but Vatsim mode errors on Euroscope to: 
![image](https://user-images.githubusercontent.com/16664350/101364690-84974000-38ab-11eb-8bcf-104355e1e807.png)

**Comment by Sequal32** [comment]
@rkantos New release out for EuroScope support ;)

**Comment by rkantos** [comment]
> @rkantos New release out for EuroScope support ;)

Thanks! If it matters, Euroscope should be able to connect to servers without the FSD version number too with "connect to VATSIM" unselected. https://github.com/nguyenquyhy/Flight-Events/blob/master/FlightEvents.Client.ATC/ATCServer.cs#L122

"Vatsim mode" should only be needed for VRC I guess :)
