### ISSUE TITLE
Error fetching data from ADSBExchange!

### ISSUE THREAD

**Issue by ghost** [Sequal32/vrclivetraffic#6]
While running the executable I keep getting this error:

`Error fetching data from ADSBExchange! Reason: RequestFailed(Error(StatusCode(429)))`

![image](https://user-images.githubusercontent.com/63513308/114314177-9beb7180-9ac7-11eb-8520-a39070224ad7.png)

**Comment by MatisseBE** [comment]
I have the same issue after a little over 5 updates.
![image](https://user-images.githubusercontent.com/51272243/114383042-5f824900-9b8d-11eb-8947-e31a86bb0cb0.png)

**Comment by Sequal32** [comment]
Thanks! Release 1.4.0 fixes this.
