### ISSUE TITLE
Aircraft meta data - 2

### ISSUE THREAD

**Issue by MatisseBE** [Sequal32/vrclivetraffic#7]
Thanks for the updated release!

With regards to my previous (closed) issue "Aircraft meta data", I'd like to report the following: 

-Config: "use_flightaware": **false** & "prefer_flight_radar": true. 
-I have disabled flightaware because here in Europe, flightaware doesn't support routes. I get the following:
![image](https://user-images.githubusercontent.com/51272243/115148030-0e2afb80-a05e-11eb-8036-ac8534f08f0f.png)
The white tagged aircraft (2) are aircraft of whom I have received ADAP/ADES. For all grey aircraft I have received no ADAP/ADES and only sometims ATYP. I assume this should not happen as per last issue, all of this information is retrieved.

Then,

-Config: "use_flightaware": **true** & "prefer_flight_radar": true
I can't truely show this in a screenshot due to hidden tag items, but I get the following:
Some aircraft have ADEP/ADES, but some don't. Again, this should be covered by FR right? Due to FlightAware's poor data here, most aircraft have only ADEP, without ADES, can this get covered too by FR? ATPY is mostly present.

Importantly, with this configuration I've also seen a few aircraft with a coordinate as ADEP. Two examples:
![image](https://user-images.githubusercontent.com/51272243/115148729-349e6600-a061-11eb-92cb-cf45946b555f.png)
![image](https://user-images.githubusercontent.com/51272243/115148737-41bb5500-a061-11eb-8ed6-8ee9add6753a.png)
The coordinate does not change after position updates.

Thanks again, I hope you appreciate the feedback.

**Comment by Sequal32** [comment]
Okay so hopefully this next release is more reliable with filling in flightplans. However, sometimes FR24 is unable to provide origin/destination data so just crosscheck with their website before reporting it (sometimes there's only a origin, sometimes neither). Additionally, this is undocumented behavior but ADSBExchange data sometimes goes outside of the range you define in the config file, so FR24's data will not get filled in for those aircraft.

**Comment by MatisseBE** [comment]
That undocumented behavior is very likely to be the main cause! Thanks for clearing that up!

**Comment by Sequal32** [comment]
I've documented this behavior in the Readme now.
