### ISSUE TITLE
Attempt to calculate the remainder with devisor zero

### ISSUE THREAD

**Issue by MatisseBE** [Sequal32/vrclivetraffic#8]
I got this when starting the application from the taskbar like I always do. Trying again via the livetraffic folder (where the exe resides), I dont get the error.

![image](https://user-images.githubusercontent.com/51272243/115898667-1ae49080-a45e-11eb-98b4-d7f9497ac5a3.png)

Since the error is point to adsbexchange, it might be interesting to note I get "too many requests" as soon as I connect using the exe in the folder: 
![image](https://user-images.githubusercontent.com/51272243/115899718-621f5100-a45f-11eb-93c3-8a19e2962268.png)

**Comment by Sequal32** [comment]
Fixed in 1.4.2!
